services:
  - name: thatsmartsite
    type: web
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/Thanthou/thatsmartsite
    branch: main
    rootDir: .
    autoDeployTrigger: commit

    buildCommand: |
      echo "==> Starting 3-layer architecture build process..."
      
      # Backend setup
      echo "==> Installing backend dependencies..."
      cd backend
      npm ci
      echo "==> Fixing debug module..."
      rm -rf node_modules/debug
      npm install debug --force
      echo "==> Installing critical runtime dependencies..."
      npm install bcryptjs express pg cors dotenv jsonwebtoken

      # Frontend setup
      echo "==> Installing frontend dependencies..."
      cd ../frontend
      npm ci --include=dev
      echo "==> Building 3-layer frontend (main, admin, tenant)..."
      npm run build

      # Validate build output
      echo "==> Validating build structure..."
      if [ ! -f "dist/main/index.html" ]; then
        echo "❌ ERROR: Main site build missing!"
        exit 1
      fi
      if [ ! -f "dist/admin/index.html" ]; then
        echo "❌ ERROR: Admin app build missing!"
        exit 1
      fi
      if [ ! -f "dist/tenant/index.html" ]; then
        echo "❌ ERROR: Tenant app build missing!"
        exit 1
      fi
      echo "✅ All 3 builds validated successfully!"

      # Prepare backend public directory
      echo "==> Preparing backend/public for 3-layer deployment..."
      cd ..
      rm -rf backend/public
      mkdir -p backend/public/{main,admin,tenant}

      # Copy builds (using current Vite output structure)
      echo "==> Copying main site build..."
      cp -r frontend/dist/src/main-site/* backend/public/main/
      echo "==> Copying admin app build..."
      cp -r frontend/dist/src/admin-app/* backend/public/admin/
      echo "==> Copying tenant app build..."
      cp -r frontend/dist/src/tenant-app/* backend/public/tenant/

      # Final validation
      echo "==> Final deployment structure validation..."
      echo "Main site: $(find backend/public/main -name 'index.html' | wc -l) files"
      echo "Admin app: $(find backend/public/admin -name 'index.html' | wc -l) files"
      echo "Tenant app: $(find backend/public/tenant -name 'index.html' | wc -l) files"
      
      if [ $(find backend/public -name 'index.html' | wc -l) -ne 3 ]; then
        echo "❌ ERROR: Expected 3 index.html files, found $(find backend/public -name 'index.html' | wc -l)"
        exit 1
      fi

      echo "✅ 3-layer architecture build completed successfully!"

    startCommand: |
      echo "==> Current working directory: $(pwd)"
      echo "==> Checking if server.js exists and printing its first 10 lines:"
      head backend/server.js
      echo "==> PORT: $PORT"
      echo "==> NODE_ENV: $NODE_ENV"
      echo "==> DATABASE_URL exists: $([ -n "$DATABASE_URL" ] && echo "YES" || echo "NO")"
      cd backend
      echo "==> Starting server directly..."
      node server.js

    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: thatsmartsite-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_PAGESPEED_API_KEY
        sync: false
      - key: ADMIN_EMAILS
        value: admin@thatsmartsite.com
      - key: ADMIN_EMAIL
        value: admin@thatsmartsite.com
      - key: ADMIN_PASSWORD
        value: ThatsSmartSite2024!SecureAdmin
      - key: ADMIN_NAME
        value: Brandan Coleman
      - key: ALLOWED_ORIGINS
        value: https://thatsmartsite.com,https://www.thatsmartsite.com

databases:
  - name: thatsmartsite-db
    plan: basic-256mb
    region: oregon
    ipAllowList: []
