services:
  - name: thatsmartsite
    type: web
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/Thanthou/thatsmartsite
    branch: main
    rootDir: .
    autoDeployTrigger: commit

    buildCommand: |
      echo "==> Installing backend dependencies..."
      cd backend
      npm install
      echo "==> Fixing debug module..."
      rm -rf node_modules/debug
      npm install debug --force
      echo "==> Installing critical runtime dependencies..."
      npm install bcryptjs express pg cors dotenv jsonwebtoken

      echo "==> Installing frontend dependencies..."
      cd ../frontend
      npm install --include=dev
      echo "==> Building frontend with dual entry points..."
      npm run build
      echo "==> Replacing backend/public with fresh build (atomic copy)..."
      rm -rf ../backend/public
      mkdir -p ../backend/public
      cp -r dist/* ../backend/public/
      echo "==> Final verification..."
      ls -la ../backend/public/

    startCommand: |
      echo "==> Current working directory: $(pwd)"
      echo "==> Checking if server.js exists and printing its first 10 lines:"
      head backend/server.js
      echo "==> PORT: $PORT"
      echo "==> NODE_ENV: $NODE_ENV"
      echo "==> DATABASE_URL exists: $([ -n "$DATABASE_URL" ] && echo "YES" || echo "NO")"
      cd backend
      echo "==> Starting server directly..."
      node server.js

    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: thatsmartsite-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: GOOGLE_PAGESPEED_API_KEY
        sync: false
      - key: ADMIN_EMAILS
        value: admin@thatsmartsite.com
      - key: ADMIN_EMAIL
        value: admin@thatsmartsite.com
      - key: ADMIN_PASSWORD
        value: ThatsSmartSite2024!SecureAdmin
      - key: ADMIN_NAME
        value: Brandan Coleman
      - key: ALLOWED_ORIGINS
        value: https://thatsmartsite.com,https://www.thatsmartsite.com

databases:
  - name: thatsmartsite-db
    plan: basic-256mb
    region: oregon
    ipAllowList: []  # internal access only
