# Render.com Full-Stack Deployment Configuration
# This deploys both frontend and backend on Render

services:
  # Backend API Service
  - type: web
    name: thatsmartsite-backend
    env: node
    plan: starter
    buildCommand: |
      cd backend && npm install
      npm run migrate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: thatsmartsite-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_EMAILS
        value: admin@thatsmartsite.com
      - key: ALLOWED_ORIGINS
        value: https://thatsmartsite.com,https://www.thatsmartsite.com
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: thatsmartsite-frontend
    env: static
    buildCommand: |
      cd frontend && npm install
      npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://thatsmartsite-backend.onrender.com
      - key: VITE_APP_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

  # PostgreSQL Database
  - type: pserv
    name: thatsmartsite-db
    plan: starter
    databaseName: thatsmartsite
    user: thatsmartsite_user
    autoDeploy: true
