services:
  - name: thatsmartsite
    type: web
    runtime: node
    plan: starter
    region: oregon
    repo: https://github.com/Thanthou/thatsmartsite
    branch: main
    rootDir: .
    autoDeployTrigger: commit

    buildCommand: |
      echo "==> Installing backend dependencies..."
      cd backend
      npm install --omit=dev
      echo "==> Installing critical runtime dependencies..."
      npm install bcryptjs express pg cors dotenv jsonwebtoken
      echo "==> Verifying bcryptjs installation..."
      ls -la node_modules/bcryptjs/ || echo "ERROR: bcryptjs missing!"
      echo "==> Running database migrations..."
      npm run migrate

      echo "==> Installing frontend dependencies..."
      cd ../frontend
      npm install --include=dev
      echo "==> Building frontend..."
      npm run build

      echo "==> Copying frontend build to backend public directory..."
      mkdir -p ../backend/public
      cp -r dist/* ../backend/public/
      echo "==> Final verification..."
      ls -la ../backend/public/ || echo "ERROR: Frontend build not copied!"

    startCommand: cd backend && npm start
    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: thatsmartsite-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_EMAILS
        value: admin@thatsmartsite.com
      - key: ALLOWED_ORIGINS
        value: https://thatsmartsite.com,https://www.thatsmartsite.com

databases:
  - name: thatsmartsite-db
    plan: basic-256mb
    region: oregon
    ipAllowList: []  # internal access only