// Service Area Mapping - Auto-generated from business configs
// This file is generated by scripts/generateServiceAreaMapping.js
// Do not edit directly.

export interface StateCitiesMapping {
  [state: string]: {
    [city: string]: string[]; // Array of business slugs that serve this city
  };
}

// State abbreviation to full name mapping
export const STATE_MAPPING: { [abbr: string]: string } = {
  "AL": "Alabama",
  "AK": "Alaska",
  "AZ": "Arizona",
  "AR": "Arkansas",
  "CA": "California",
  "CO": "Colorado",
  "CT": "Connecticut",
  "DE": "Delaware",
  "FL": "Florida",
  "GA": "Georgia",
  "HI": "Hawaii",
  "ID": "Idaho",
  "IL": "Illinois",
  "IN": "Indiana",
  "IA": "Iowa",
  "KS": "Kansas",
  "KY": "Kentucky",
  "LA": "Louisiana",
  "ME": "Maine",
  "MD": "Maryland",
  "MA": "Massachusetts",
  "MI": "Michigan",
  "MN": "Minnesota",
  "MS": "Mississippi",
  "MO": "Missouri",
  "MT": "Montana",
  "NE": "Nebraska",
  "NV": "Nevada",
  "NH": "New Hampshire",
  "NJ": "New Jersey",
  "NM": "New Mexico",
  "NY": "New York",
  "NC": "North Carolina",
  "ND": "North Dakota",
  "OH": "Ohio",
  "OK": "Oklahoma",
  "OR": "Oregon",
  "PA": "Pennsylvania",
  "RI": "Rhode Island",
  "SC": "South Carolina",
  "SD": "South Dakota",
  "TN": "Tennessee",
  "TX": "Texas",
  "UT": "Utah",
  "VT": "Vermont",
  "VA": "Virginia",
  "WA": "Washington",
  "WV": "West Virginia",
  "WI": "Wisconsin",
  "WY": "Wyoming"
};

// State to city to business slugs mapping
export const STATE_CITIES_MAPPING: StateCitiesMapping = {
  "Arizona": {
    "Bullhead City": [
      "jps"
    ],
    "Fort Mohave": [
      "jps"
    ],
    "Katherine Landing": [
      "jps"
    ],
    "Kingman": [
      "jps"
    ],
    "Lake Havasu City": [
      "jps"
    ],
    "Mohave Valley": [
      "jps"
    ]
  },
  "California": {
    "Needles": [
      "jps"
    ]
  },
  "Nevada": {
    "Anthem": [
      "abc"
    ],
    "Boulder City": [
      "abc"
    ],
    "Enterprise": [
      "abc"
    ],
    "Green Valley": [
      "abc"
    ],
    "Henderson": [
      "abc"
    ],
    "Las Vegas": [
      "abc"
    ],
    "Laughlin": [
      "jps"
    ],
    "Mount Charleston": [
      "abc"
    ],
    "North Las Vegas": [
      "abc"
    ],
    "Paradise": [
      "abc"
    ],
    "Red Rock Canyon": [
      "abc"
    ],
    "Spring Valley": [
      "abc"
    ],
    "Summerlin": [
      "abc"
    ],
    "Sunrise Manor": [
      "abc"
    ],
    "Valley of Fire": [
      "abc"
    ],
    "Whitney": [
      "abc"
    ],
    "Winchester": [
      "abc"
    ]
  }
};

// Utility functions
export const getStates = (): string[] => {
  return Object.keys(STATE_CITIES_MAPPING).sort();
};

export const getCitiesForState = (state: string): string[] => {
  return STATE_CITIES_MAPPING[state] ? Object.keys(STATE_CITIES_MAPPING[state]).sort() : [];
};

export const getBusinessesForCity = (state: string, city: string): string[] => {
  return STATE_CITIES_MAPPING[state] && STATE_CITIES_MAPPING[state][city]
    ? STATE_CITIES_MAPPING[state][city]
    : [];
};

export const isCityServedByBusiness = (state: string, city: string, businessSlug: string): boolean => {
  return getBusinessesForCity(state, city).includes(businessSlug);
};
