-- Initial affiliate business data seeds
-- These are sample affiliate businesses for testing and development

-- Insert sample affiliate business 1
INSERT INTO tenants.business (
    slug,
    business_name,
    first_name,
    last_name,
    user_id,
    application_status,
    business_start_date,
    business_phone,
    personal_phone,
    business_email,
    personal_email,
    twilio_phone,
    gbp_url,
    facebook_url,
    instagram_url,
    youtube_url,
    tiktok_url,
    source,
    notes,
    service_areas,
    application_date,
    approved_date,
    last_activity,
    created_at,
    updated_at
) VALUES (
    'jps',
    'JP''s Mobile Detailing',
    'Jess',
    'Brister',
    2, -- References the affiliate user from auth_users.sql
    'approved',
    '2020-01-15',
    '7024203151',
    '7024203151',
    'jpsmobiledetailing@hotmail.com',
    'jessbrister27@gmail.com',
    '+17024203151',
    'https://share.google/3wFWowHO1VIVrPHRd',
    'https://www.facebook.com/JPsMobileDetailing928/',
    '',
    '',
    '',
    'website',
    'Premium mobile detailing services in Las Vegas area',
    '[
        {
            "city": "Bullhead City",
            "state": "AZ",
            "zip": "86442",
            "primary": true
        },
        {
            "city": "Fort Mohave",
            "state": "AZ"
        },
        {
            "city": "Mohave Valley",
            "state": "AZ"
        },
        {
            "city": "Lake Havasu City",
            "state": "AZ",
            "minimum": 1000,
            "multiplier": 1.1
        },
        {
            "city": "Needles",
            "state": "CA"
        },
        {
            "city": "Laughlin",
            "state": "NV"
        },
        {
            "city": "Las Vegas",
            "state": "NV",
            "zip": "89002",
            "minimum": 1000,
            "multiplier": 1.25
        }
    ]'::jsonb,
    '2025-08-28 18:45:00.933574-07',
    '2025-08-28 19:00:00.000000-07',
    '2025-08-28 19:00:00.000000-07',
    '2025-08-28 18:45:00.933574-07',
    '2025-08-28 19:00:00.000000-07'
) ON CONFLICT (slug) DO UPDATE SET
    business_name = EXCLUDED.business_name,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    user_id = EXCLUDED.user_id,
    application_status = EXCLUDED.application_status,
    business_start_date = EXCLUDED.business_start_date,
    business_phone = EXCLUDED.business_phone,
    personal_phone = EXCLUDED.personal_phone,
    business_email = EXCLUDED.business_email,
    personal_email = EXCLUDED.personal_email,
    twilio_phone = EXCLUDED.twilio_phone,
    gbp_url = EXCLUDED.gbp_url,
    facebook_url = EXCLUDED.facebook_url,
    instagram_url = EXCLUDED.instagram_url,
    youtube_url = EXCLUDED.youtube_url,
    tiktok_url = EXCLUDED.tiktok_url,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes,
    service_areas = EXCLUDED.service_areas,
    application_date = EXCLUDED.application_date,
    approved_date = EXCLUDED.approved_date,
    last_activity = EXCLUDED.last_activity,
    updated_at = EXCLUDED.updated_at;

-- Insert sample affiliate business 2
INSERT INTO tenants.business (
    slug,
    business_name,
    first_name,
    last_name,
    user_id,
    application_status,
    business_start_date,
    business_phone,
    personal_phone,
    business_email,
    personal_email,
    twilio_phone,
    gbp_url,
    facebook_url,
    instagram_url,
    youtube_url,
    tiktok_url,
    source,
    notes,
    service_areas,
    application_date,
    approved_date,
    last_activity,
    created_at,
    updated_at
) VALUES (
    'premium-auto-spa',
    'Premium Auto Spa',
    'Mike',
    'Johnson',
    null, -- No user account yet
    'approved',
    '2019-06-01',
    '5551234567',
    '5551234567',
    'mike@premiumautospa.com',
    'mike.johnson@email.com',
    '+15551234567',
    'https://g.page/premium-auto-spa',
    'https://facebook.com/premiumautospa',
    'https://instagram.com/premiumautospa',
    null,
    'https://tiktok.com/@premiumautospa',
    'referral',
    'High-end detailing services with ceramic coating',
    '[
        {
            "city": "Phoenix",
            "state": "AZ",
            "primary": true
        },
        {
            "city": "Scottsdale",
            "state": "AZ",
            "zip": "85251"
        },
        {
            "city": "Tempe",
            "state": "AZ",
            "zip": "85281"
        }
    ]'::jsonb,
    '2025-08-29 10:00:00.000000-07',
    '2025-08-29 10:30:00.000000-07',
    '2025-08-29 10:30:00.000000-07',
    '2025-08-29 10:00:00.000000-07',
    '2025-08-29 10:30:00.000000-07'
) ON CONFLICT (slug) DO UPDATE SET
    business_name = EXCLUDED.business_name,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    user_id = EXCLUDED.user_id,
    application_status = EXCLUDED.application_status,
    business_start_date = EXCLUDED.business_start_date,
    business_phone = EXCLUDED.business_phone,
    personal_phone = EXCLUDED.personal_phone,
    business_email = EXCLUDED.business_email,
    personal_email = EXCLUDED.personal_email,
    twilio_phone = EXCLUDED.twilio_phone,
    gbp_url = EXCLUDED.gbp_url,
    facebook_url = EXCLUDED.facebook_url,
    instagram_url = EXCLUDED.instagram_url,
    youtube_url = EXCLUDED.youtube_url,
    tiktok_url = EXCLUDED.tiktok_url,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes,
    service_areas = EXCLUDED.service_areas,
    application_date = EXCLUDED.application_date,
    approved_date = EXCLUDED.approved_date,
    last_activity = EXCLUDED.last_activity,
    updated_at = EXCLUDED.updated_at;

-- Insert sample affiliate business 3 (pending approval)
INSERT INTO tenants.business (
    slug,
    business_name,
    first_name,
    last_name,
    user_id,
    application_status,
    business_start_date,
    business_phone,
    personal_phone,
    business_email,
    personal_email,
    twilio_phone,
    gbp_url,
    facebook_url,
    instagram_url,
    youtube_url,
    tiktok_url,
    source,
    notes,
    service_areas,
    application_date,
    approved_date,
    last_activity,
    created_at,
    updated_at
) VALUES (
    'elite-mobile-detail',
    'Elite Mobile Detail',
    'Sarah',
    'Williams',
    null,
    'pending',
    '2021-03-15',
    '5559876543',
    '5559876543',
    'sarah@elitemobiledetail.com',
    'sarah.williams@email.com',
    '+15559876543',
    null,
    'https://facebook.com/elitemobiledetail',
    'https://instagram.com/elitemobiledetail',
    'https://youtube.com/@elitemobiledetail',
    null,
    'google',
    'New business looking to expand service area',
    '[
        {
            "city": "Los Angeles",
            "state": "CA",
            "zip": "90001"
        },
        {
            "city": "Beverly Hills",
            "state": "CA",
            "zip": "90210"
        }
    ]'::jsonb,
    '2025-08-30 14:00:00.000000-07',
    null, -- Not approved yet
    '2025-08-30 14:00:00.000000-07',
    '2025-08-30 14:00:00.000000-07',
    '2025-08-30 14:00:00.000000-07'
) ON CONFLICT (slug) DO UPDATE SET
    business_name = EXCLUDED.business_name,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    user_id = EXCLUDED.user_id,
    application_status = EXCLUDED.application_status,
    business_start_date = EXCLUDED.business_start_date,
    business_phone = EXCLUDED.business_phone,
    personal_phone = EXCLUDED.personal_phone,
    business_email = EXCLUDED.business_email,
    personal_email = EXCLUDED.personal_email,
    twilio_phone = EXCLUDED.twilio_phone,
    gbp_url = EXCLUDED.gbp_url,
    facebook_url = EXCLUDED.facebook_url,
    instagram_url = EXCLUDED.instagram_url,
    youtube_url = EXCLUDED.youtube_url,
    tiktok_url = EXCLUDED.tiktok_url,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes,
    service_areas = EXCLUDED.service_areas,
    application_date = EXCLUDED.application_date,
    approved_date = EXCLUDED.approved_date,
    last_activity = EXCLUDED.last_activity,
    updated_at = EXCLUDED.updated_at;

-- Insert sample affiliate business 4 (approved with minimal data)
INSERT INTO tenants.business (
    slug,
    business_name,
    first_name,
    last_name,
    user_id,
    application_status,
    business_start_date,
    business_phone,
    personal_phone,
    business_email,
    personal_email,
    twilio_phone,
    gbp_url,
    facebook_url,
    instagram_url,
    youtube_url,
    tiktok_url,
    source,
    notes,
    service_areas,
    application_date,
    approved_date,
    last_activity,
    created_at,
    updated_at
) VALUES (
    'quick-clean-mobile',
    'Quick Clean Mobile',
    'David',
    'Brown',
    null,
    'approved',
    '2022-01-01',
    '5555551234',
    null,
    'david@quickcleanmobile.com',
    null,
    '+15555551234',
    null,
    null,
    null,
    null,
    null,
    'direct',
    'Basic mobile detailing services',
    '[
        {
            "city": "Austin",
            "state": "TX",
            "zip": "73301"
        }
    ]'::jsonb,
    '2025-08-31 09:00:00.000000-07',
    '2025-08-31 09:15:00.000000-07',
    '2025-08-31 09:15:00.000000-07',
    '2025-08-31 09:00:00.000000-07',
    '2025-08-31 09:15:00.000000-07'
) ON CONFLICT (slug) DO UPDATE SET
    business_name = EXCLUDED.business_name,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    user_id = EXCLUDED.user_id,
    application_status = EXCLUDED.application_status,
    business_start_date = EXCLUDED.business_start_date,
    business_phone = EXCLUDED.business_phone,
    personal_phone = EXCLUDED.personal_phone,
    business_email = EXCLUDED.business_email,
    personal_email = EXCLUDED.personal_email,
    twilio_phone = EXCLUDED.twilio_phone,
    gbp_url = EXCLUDED.gbp_url,
    facebook_url = EXCLUDED.facebook_url,
    instagram_url = EXCLUDED.instagram_url,
    youtube_url = EXCLUDED.youtube_url,
    tiktok_url = EXCLUDED.tiktok_url,
    source = EXCLUDED.source,
    notes = EXCLUDED.notes,
    service_areas = EXCLUDED.service_areas,
    application_date = EXCLUDED.application_date,
    approved_date = EXCLUDED.approved_date,
    last_activity = EXCLUDED.last_activity,
    updated_at = EXCLUDED.updated_at;
