-- Seed data for reputation schema - Sample reviews
-- This file contains sample reviews for both affiliates and MDH site

-- Insert sample affiliate reviews
INSERT INTO reputation.reviews (
    review_type,
    affiliate_id,
    business_slug,
    rating,
    title,
    content,
    reviewer_name,
    reviewer_email,
    reviewer_avatar_url,
    review_source,
    status,
    is_verified,
    service_category,
    service_date,
    is_featured,
    published_at
) VALUES 
-- Reviews for "jps" (JP's Mobile Detailing) - affiliate_id = 1
(
    'affiliate',
    1,
    'jps',
    5,
    'Amazing paint correction work!',
    'Jess and his team did an incredible job on my 2019 BMW. The paint correction was flawless and the ceramic coating looks amazing. Very professional and showed up exactly on time. Highly recommend!',
    'Sarah Johnson',
    'sarah.johnson@email.com',
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'paint_correction',
    '2024-01-15',
    true,
    '2024-01-16 10:30:00+00'
),
(
    'affiliate',
    1,
    'jps',
    5,
    'Best detailing service in town',
    'I''ve used several detailing services before, but JP''s Mobile Detailing is by far the best. They''re thorough, professional, and the results speak for themselves. My car looks brand new!',
    'Mike Chen',
    'mike.chen@email.com',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'auto',
    '2024-01-20',
    false,
    '2024-01-21 14:15:00+00'
),
(
    'affiliate',
    1,
    'jps',
    4,
    'Great service, minor scheduling issue',
    'The work was excellent and my car looks fantastic. Had a small issue with scheduling - they were running about 30 minutes late, but they called ahead to let me know. Overall very satisfied.',
    'Emily Rodriguez',
    'emily.rodriguez@email.com',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'ceramic',
    '2024-01-25',
    false,
    '2024-01-26 09:45:00+00'
),

-- Reviews for "premium-auto-spa" (Premium Auto Spa) - affiliate_id = 2
(
    'affiliate',
    2,
    'premium-auto-spa',
    5,
    'Outstanding ceramic coating work!',
    'Mike and his team did an incredible job on my Tesla. The ceramic coating application was flawless and the protection is amazing. Water just beads off! Very professional and explained everything clearly.',
    'Captain Tom Wilson',
    'tom.wilson@email.com',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'ceramic',
    '2024-01-18',
    true,
    '2024-01-19 16:20:00+00'
),
(
    'affiliate',
    2,
    'premium-auto-spa',
    4,
    'Professional and reliable',
    'Great service for my luxury sedan. They were very professional and completed the work on time. The car looks great and the price was fair. Would recommend to other car owners.',
    'Lisa Anderson',
    'lisa.anderson@email.com',
    'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'auto',
    '2024-01-22',
    false,
    '2024-01-23 11:30:00+00'
),

-- Reviews for "elite-mobile-detail" (Elite Mobile Detail) - affiliate_id = 3
(
    'affiliate',
    3,
    'elite-mobile-detail',
    5,
    'Perfect mobile detailing service',
    'Sarah and her team know mobile detailing! They understood all the unique challenges of mobile service and did an amazing job. The interior looks brand new and the exterior is spotless. Very impressed!',
    'Robert & Mary Thompson',
    'rthompson@email.com',
    'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'auto',
    '2024-01-17',
    true,
    '2024-01-18 13:45:00+00'
),
(
    'affiliate',
    3,
    'elite-mobile-detail',
    4,
    'Great work on our luxury SUV',
    'Very thorough cleaning of our Range Rover. They were careful with all the delicate surfaces and did a great job. Only minor issue was they were a bit behind schedule, but the quality made up for it.',
    'David Kim',
    'david.kim@email.com',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'auto',
    '2024-01-24',
    false,
    '2024-01-25 15:10:00+00'
),

-- Reviews for "quick-clean-mobile" (Quick Clean Mobile) - affiliate_id = 4
(
    'affiliate',
    4,
    'quick-clean-mobile',
    5,
    'Incredible quick service results',
    'David and his team provided amazing quick clean service. My car has never looked this good and the turnaround time was incredible. Water just beads off! The team was very professional and explained everything clearly.',
    'Jennifer Martinez',
    'jennifer.martinez@email.com',
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    'auto',
    '2024-01-19',
    true,
    '2024-01-20 12:00:00+00'
),

-- MDH Site Reviews
(
    'mdh',
    NULL,
    NULL,
    5,
    'Easy to find great detailing services',
    'This platform made it so easy to find and book a detailing service in my area. The booking process was smooth and I could see all the available services and prices upfront. Great experience!',
    'Alex Thompson',
    'alex.thompson@email.com',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    NULL,
    NULL,
    true,
    '2024-01-21 08:30:00+00'
),
(
    'mdh',
    NULL,
    NULL,
    5,
    'Loved the variety of services available',
    'This platform made it so easy to find and book a detailing service in my area. The booking process was smooth and I could see all the available services and prices upfront. Great experience!',
    'Mr. Thompson',
    'alex2.thompson@email.com',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    'yelp',
    'approved',
    true,
    NULL,
    NULL,
    true,
    '2023-01-21 08:30:00+00'
),
(
    'mdh',
    NULL,
    NULL,
    4,
    'Good platform, could use more features',
    'Overall a great platform for finding detailing services. The interface is clean and easy to use. Would love to see more filtering options and maybe a chat feature with the service providers.',
    'Rachel Green',
    'rachel.green@email.com',
    'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    NULL,
    NULL,
    false,
    '2024-01-23 14:20:00+00'
),
(
    'mdh',
    NULL,
    NULL,
    5,
    'Excellent customer service',
    'Had a small issue with my booking and the customer service team resolved it quickly and professionally. The platform itself is great and I''ve used it multiple times now. Highly recommend!',
    'Mark Davis',
    'mark.davis@email.com',
    'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    'website',
    'approved',
    true,
    NULL,
    NULL,
    false,
    '2024-01-26 10:15:00+00'
),
(
    'mdh',
    NULL,
    NULL,
    5,
    'Fantastic platform for mobile detailing',
    'I''ve used this platform multiple times now and it never disappoints. The booking process is smooth, the service providers are professional, and the results are always excellent. Highly recommend to anyone looking for quality mobile detailing services!',
    'Jennifer Smith',
    'jennifer.smith@email.com',
    'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    'google',
    'approved',
    true,
    NULL,
    NULL,
    false,
    '2024-01-28 16:45:00+00'
);

-- Insert some sample review replies from business owners
-- Note: These will be added after reviews are inserted to avoid foreign key issues

-- Insert some sample review votes
-- Note: These will be added after reviews are inserted to avoid foreign key issues

-- Update helpful_votes and total_votes counts
-- Note: These will be updated after votes are inserted
