import { Review } from './types';

export const mockReviews: Review[] = [
  {
    id: '1',
    customerName: 'Sarah Johnson',
    rating: 5,
    reviewText: 'Absolutely incredible service! My car looks better than the day I bought it. The attention to detail is unmatched and the team was professional throughout the entire process. Highly recommend!',
    date: '2024-01-15',
    isVerified: true,
  },
  {
    id: '2',
    customerName: 'Michael Chen',
    rating: 5,
    reviewText: 'Best mobile detailing service in the area! They came to my office and transformed my SUV. The ceramic coating they applied has kept my vehicle looking pristine for months.',
    date: '2024-01-10',
    isVerified: true,
  },
  {
    id: '3',
    customerName: 'Emily Rodriguez',
    rating: 5,
    reviewText: 'Outstanding work! The interior detailing removed stains I thought were permanent. Very reasonable prices for such high-quality service. Will definitely be using them again.',
    date: '2024-01-08',
    isVerified: true,
  },
  {
    id: '4',
    customerName: 'David Thompson',
    rating: 5,
    reviewText: 'Professional, punctual, and perfectionist! They spent hours ensuring every detail was perfect. My luxury sedan has never looked better. Worth every penny!',
    date: '2024-01-05',
    isVerified: true,
  },
  {
    id: '5',
    customerName: 'Lisa Zhang',
    rating: 5,
    reviewText: 'Exceptional service from start to finish. The team was courteous, efficient, and the results exceeded my expectations. My car sparkles like new!',
    date: '2024-01-03',
    isVerified: true,
  },
  {
    id: '6',
    customerName: 'Robert Williams',
    rating: 5,
    reviewText: 'These guys are artists! The paint correction work they did on my classic car was phenomenal. True professionals who take pride in their craft.',
    date: '2024-01-01',
    isVerified: true,
  },
  {
    id: '7',
    customerName: 'Jennifer Martinez',
    rating: 5,
    reviewText: 'Incredible attention to detail! They transformed my truck from looking worn out to showroom quality. The team was professional and the results speak for themselves.',
    date: '2023-12-28',
    isVerified: true,
  },
  {
    id: '8',
    customerName: 'Kevin Park',
    rating: 4,
    reviewText: 'Great service overall. My car looks fantastic and the team was very professional. Only minor issue was they were running a bit late, but the quality made up for it.',
    date: '2023-12-25',
    isVerified: true,
  },
  {
    id: '9',
    customerName: 'Amanda Foster',
    rating: 5,
    reviewText: 'Best investment I\'ve made for my vehicle! The ceramic coating has kept my car looking pristine through all weather conditions. Highly professional service.',
    date: '2023-12-20',
    isVerified: true,
  },
];